#############################################################################
# Makefile for building: bin/prueba1
# Generated by qmake (2.01a) (Qt 4.7.1) on: jue nov 11 00:29:05 2010
# Project:  prueba1.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/share/qt/mkspecs/linux-g++-64 CONFIG+=debug -o Makefile prueba1.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -march=x86-64 -mtune=generic -O2 -pipe -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -march=x86-64 -mtune=generic -O2 -pipe -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt/mkspecs/linux-g++-64 -I. -I/usr/include/QtCore -I/usr/include/QtNetwork -I/usr/include/QtGui -I/usr/include -Ibuild -Ibuild
LINK          = g++
LFLAGS        = -m64 -Wl,--hash-style=gnu -Wl,--as-needed -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lcurl -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = build/

####### Files

SOURCES       = src/mainwindowimpl.cpp \
		src/main.cpp \
		src/downloader.cpp \
		src/megaupload.cpp \
		src/link.cpp \
		src/download_handler.cpp \
		src/downloadmanager.cpp \
		src/textprogressbar.cpp build/moc_mainwindowimpl.cpp \
		build/moc_downloadmanager.cpp \
		qrc_resource.cpp
OBJECTS       = build/mainwindowimpl.o \
		build/main.o \
		build/downloader.o \
		build/megaupload.o \
		build/link.o \
		build/download_handler.o \
		build/downloadmanager.o \
		build/textprogressbar.o \
		build/moc_mainwindowimpl.o \
		build/moc_downloadmanager.o \
		build/qrc_resource.o
DIST          = /usr/share/qt/mkspecs/common/g++.conf \
		/usr/share/qt/mkspecs/common/unix.conf \
		/usr/share/qt/mkspecs/common/linux.conf \
		/usr/share/qt/mkspecs/qconfig.pri \
		/usr/share/qt/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt/mkspecs/features/qt_functions.prf \
		/usr/share/qt/mkspecs/features/qt_config.prf \
		/usr/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt/mkspecs/features/default_pre.prf \
		/usr/share/qt/mkspecs/features/release.prf \
		/usr/share/qt/mkspecs/features/default_post.prf \
		/usr/share/qt/mkspecs/features/warn_on.prf \
		/usr/share/qt/mkspecs/features/qt.prf \
		/usr/share/qt/mkspecs/features/unix/thread.prf \
		/usr/share/qt/mkspecs/features/moc.prf \
		/usr/share/qt/mkspecs/features/resources.prf \
		/usr/share/qt/mkspecs/features/uic.prf \
		/usr/share/qt/mkspecs/features/yacc.prf \
		/usr/share/qt/mkspecs/features/lex.prf \
		prueba1.pro
QMAKE_TARGET  = prueba1
DESTDIR       = bin/
TARGET        = bin/prueba1

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): build/ui_mainwindow.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) bin/ || $(MKDIR) bin/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: prueba1.pro  /usr/share/qt/mkspecs/linux-g++-64/qmake.conf /usr/share/qt/mkspecs/common/g++.conf \
		/usr/share/qt/mkspecs/common/unix.conf \
		/usr/share/qt/mkspecs/common/linux.conf \
		/usr/share/qt/mkspecs/qconfig.pri \
		/usr/share/qt/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt/mkspecs/features/qt_functions.prf \
		/usr/share/qt/mkspecs/features/qt_config.prf \
		/usr/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt/mkspecs/features/default_pre.prf \
		/usr/share/qt/mkspecs/features/release.prf \
		/usr/share/qt/mkspecs/features/default_post.prf \
		/usr/share/qt/mkspecs/features/warn_on.prf \
		/usr/share/qt/mkspecs/features/qt.prf \
		/usr/share/qt/mkspecs/features/unix/thread.prf \
		/usr/share/qt/mkspecs/features/moc.prf \
		/usr/share/qt/mkspecs/features/resources.prf \
		/usr/share/qt/mkspecs/features/uic.prf \
		/usr/share/qt/mkspecs/features/yacc.prf \
		/usr/share/qt/mkspecs/features/lex.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtNetwork.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt/mkspecs/linux-g++-64 CONFIG+=debug -o Makefile prueba1.pro
/usr/share/qt/mkspecs/common/g++.conf:
/usr/share/qt/mkspecs/common/unix.conf:
/usr/share/qt/mkspecs/common/linux.conf:
/usr/share/qt/mkspecs/qconfig.pri:
/usr/share/qt/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt/mkspecs/features/qt_functions.prf:
/usr/share/qt/mkspecs/features/qt_config.prf:
/usr/share/qt/mkspecs/features/exclusive_builds.prf:
/usr/share/qt/mkspecs/features/default_pre.prf:
/usr/share/qt/mkspecs/features/release.prf:
/usr/share/qt/mkspecs/features/default_post.prf:
/usr/share/qt/mkspecs/features/warn_on.prf:
/usr/share/qt/mkspecs/features/qt.prf:
/usr/share/qt/mkspecs/features/unix/thread.prf:
/usr/share/qt/mkspecs/features/moc.prf:
/usr/share/qt/mkspecs/features/resources.prf:
/usr/share/qt/mkspecs/features/uic.prf:
/usr/share/qt/mkspecs/features/yacc.prf:
/usr/share/qt/mkspecs/features/lex.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtNetwork.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt/mkspecs/linux-g++-64 CONFIG+=debug -o Makefile prueba1.pro

dist: 
	@$(CHK_DIR_EXISTS) build/prueba11.0.0 || $(MKDIR) build/prueba11.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) build/prueba11.0.0/ && $(COPY_FILE) --parents src/mainwindowimpl.h src/downloader.h src/megaupload.h src/link.h src/download_handler.h src/downloadmanager.h src/textprogressbar.h build/prueba11.0.0/ && $(COPY_FILE) --parents resource.qrc build/prueba11.0.0/ && $(COPY_FILE) --parents src/mainwindowimpl.cpp src/main.cpp src/downloader.cpp src/megaupload.cpp src/link.cpp src/download_handler.cpp src/downloadmanager.cpp src/textprogressbar.cpp build/prueba11.0.0/ && $(COPY_FILE) --parents ui/mainwindow.ui build/prueba11.0.0/ && (cd `dirname build/prueba11.0.0` && $(TAR) prueba11.0.0.tar prueba11.0.0 && $(COMPRESS) prueba11.0.0.tar) && $(MOVE) `dirname build/prueba11.0.0`/prueba11.0.0.tar.gz . && $(DEL_FILE) -r build/prueba11.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: build/moc_mainwindowimpl.cpp build/moc_downloadmanager.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/moc_mainwindowimpl.cpp build/moc_downloadmanager.cpp
build/moc_mainwindowimpl.cpp: build/ui_mainwindow.h \
		src/downloader.h \
		src/megaupload.h \
		src/downloadmanager.h \
		src/textprogressbar.h \
		src/link.h \
		src/download_handler.h \
		src/mainwindowimpl.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/mainwindowimpl.h -o build/moc_mainwindowimpl.cpp

build/moc_downloadmanager.cpp: src/textprogressbar.h \
		src/downloadmanager.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/downloadmanager.h -o build/moc_downloadmanager.cpp

compiler_rcc_make_all: qrc_resource.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resource.cpp
qrc_resource.cpp: resource.qrc \
		resource/Earth-Download-256x256.png
	/usr/bin/rcc -name resource resource.qrc -o qrc_resource.cpp

compiler_image_collection_make_all: build/qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) build/qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: build/ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) build/ui_mainwindow.h
build/ui_mainwindow.h: ui/mainwindow.ui
	/usr/bin/uic ui/mainwindow.ui -o build/ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

build/mainwindowimpl.o: src/mainwindowimpl.cpp src/mainwindowimpl.h \
		build/ui_mainwindow.h \
		src/downloader.h \
		src/megaupload.h \
		src/downloadmanager.h \
		src/textprogressbar.h \
		src/link.h \
		src/download_handler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/mainwindowimpl.o src/mainwindowimpl.cpp

build/main.o: src/main.cpp src/mainwindowimpl.h \
		build/ui_mainwindow.h \
		src/downloader.h \
		src/megaupload.h \
		src/downloadmanager.h \
		src/textprogressbar.h \
		src/link.h \
		src/download_handler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/main.o src/main.cpp

build/downloader.o: src/downloader.cpp src/downloader.h \
		src/megaupload.h \
		src/downloadmanager.h \
		src/textprogressbar.h \
		src/link.h \
		src/download_handler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/downloader.o src/downloader.cpp

build/megaupload.o: src/megaupload.cpp src/megaupload.h \
		src/downloadmanager.h \
		src/textprogressbar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/megaupload.o src/megaupload.cpp

build/link.o: src/link.cpp src/link.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/link.o src/link.cpp

build/download_handler.o: src/download_handler.cpp src/download_handler.h \
		src/link.h \
		src/megaupload.h \
		src/downloadmanager.h \
		src/textprogressbar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/download_handler.o src/download_handler.cpp

build/downloadmanager.o: src/downloadmanager.cpp src/downloadmanager.h \
		src/textprogressbar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/downloadmanager.o src/downloadmanager.cpp

build/textprogressbar.o: src/textprogressbar.cpp src/textprogressbar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/textprogressbar.o src/textprogressbar.cpp

build/moc_mainwindowimpl.o: build/moc_mainwindowimpl.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_mainwindowimpl.o build/moc_mainwindowimpl.cpp

build/moc_downloadmanager.o: build/moc_downloadmanager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_downloadmanager.o build/moc_downloadmanager.cpp

build/qrc_resource.o: qrc_resource.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/qrc_resource.o qrc_resource.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

